# arxivの学問領域の指定
subject: 'cat:cs.CV'

# 検索キーワード
keywords:
        medical: 5
        sports: 3
        attention: 2
        segmentation: 1
        detection: 1
        semantic: 1
        anomaly: 1
# 通知の閾値
score_threshold: 0
